[package]
name = "banksea-oracle-example"
version = "0.3.0"
edition = "2018"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.3"
solana-program = "=1.10.29"
banksea-oracle-client = "0.4.0"
[lib]
crate-type = ["cdylib", "lib"]
