[package]
name = "banksea-oracle-example"
version = "0.1.0"
edition = "2018"

[dependencies]
borsh = "0.9.1"
borsh-derive = "0.9.1"
solana-program = "=1.8.1"
banksea-oracle = { path = "../banksea-oracle-rs" }
[lib]
crate-type = ["cdylib", "lib"]
